name: vytrvej
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  syncfusion_flutter_charts: ^25.1.39+1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/PiggyBankBG.png
  fonts:
    - family: HappyMonkey
      fonts:
        - asset: assets/fonts/HappyMonkey-Regular.ttf

